sudo: required
services: 
  - docker

before_install:
  - docker build -t piusoj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true piusoj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-679843633579"
  bucket_path: "Docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"